# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "zip_code", # <download_dataset>
  "most_utilized_procedure_code_for_new_patient", # <download_dataset>
  "min_medicare_pricing_for_new_patient", # <download_dataset>
  "max_medicare_pricing_for_new_patient", # <download_dataset>
  "mode_medicare_pricing_for_new_patient", # <download_dataset>
  "min_copay_for_new_patient", # <download_dataset>
  "max_copay_for_new_patient", # <download_dataset>
  "mode_copay_for_new_patient", # <download_dataset>
  "most_utilized_procedure_code_for_established_patient", # <download_dataset>
  "min_medicare_pricing_for_established_patient", # <download_dataset>
  "max_medicare_pricing_for_established_patient", # <download_dataset>
  "mode_medicare_pricing_for_established_patient", # <download_dataset>
  "min_copay_for_established_patient", # <download_dataset>
  "max_copay_for_established_patient", # <download_dataset>
  "mode_copay_for_established_patient", # <download_dataset>
  "new_code", # <download_dataset>
  "stat", # <download_dataset>
  "amount", # <download_dataset>
  "est_code", # <download_dataset>
  "zip_code", # <download_dataset_purrr>
  "most_utilized_procedure_code_for_new_patient", # <download_dataset_purrr>
  "min_medicare_pricing_for_new_patient", # <download_dataset_purrr>
  "max_medicare_pricing_for_new_patient", # <download_dataset_purrr>
  "mode_medicare_pricing_for_new_patient", # <download_dataset_purrr>
  "min_copay_for_new_patient", # <download_dataset_purrr>
  "max_copay_for_new_patient", # <download_dataset_purrr>
  "mode_copay_for_new_patient", # <download_dataset_purrr>
  "most_utilized_procedure_code_for_established_patient", # <download_dataset_purrr>
  "min_medicare_pricing_for_established_patient", # <download_dataset_purrr>
  "max_medicare_pricing_for_established_patient", # <download_dataset_purrr>
  "mode_medicare_pricing_for_established_patient", # <download_dataset_purrr>
  "min_copay_for_established_patient", # <download_dataset_purrr>
  "max_copay_for_established_patient", # <download_dataset_purrr>
  "mode_copay_for_established_patient", # <download_dataset_purrr>
  "new_code", # <download_dataset_purrr>
  "stat", # <download_dataset_purrr>
  "amount", # <download_dataset_purrr>
  "est_code", # <download_dataset_purrr>
  "csv_url", # <download_datasets>
  "filename", # <download_datasets>
  "issued", # <search_datasets>
  "modified", # <search_datasets>
  "released", # <search_datasets>
  "theme", # <search_datasets>
  "title", # <search_datasets>
  "distribution", # <search_datasets>
  "distribution.downloadURL", # <search_datasets>
  "specialty", # <use_zipcoder>
  "city", # <use_zipcoder>
  "county", # <use_zipcoder>
  "state", # <use_zipcoder>
  "zip_code", # <use_zipcoder>
  "state_region", # <use_zipcoder>
  NULL
))
