# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "zip_code", # <download_dataset>
  "most_utilized_procedure_code_for_new_patient", # <download_dataset>
  "min_medicare_pricing_for_new_patient", # <download_dataset>
  "max_medicare_pricing_for_new_patient", # <download_dataset>
  "mode_medicare_pricing_for_new_patient", # <download_dataset>
  "min_copay_for_new_patient", # <download_dataset>
  "max_copay_for_new_patient", # <download_dataset>
  "mode_copay_for_new_patient", # <download_dataset>
  "most_utilized_procedure_code_for_established_patient", # <download_dataset>
  "min_medicare_pricing_for_established_patient", # <download_dataset>
  "max_medicare_pricing_for_established_patient", # <download_dataset>
  "mode_medicare_pricing_for_established_patient", # <download_dataset>
  "min_copay_for_established_patient", # <download_dataset>
  "max_copay_for_established_patient", # <download_dataset>
  "mode_copay_for_established_patient", # <download_dataset>
  "issued", # <search_datasets>
  "modified", # <search_datasets>
  "released", # <search_datasets>
  "theme", # <search_datasets>
  "keyword", # <search_datasets>
  "distribution", # <search_datasets>
  "distribution.downloadURL", # <search_datasets>
  "city", # <use_zipcoder>
  "county", # <use_zipcoder>
  "state", # <use_zipcoder>
  "zip_code", # <use_zipcoder>
  ".data", # <use_zipcoder_tidytable>
  "zip_code", # <use_zipcoder_tidytable>
  "zip_info", # <use_zipcoder_tidytable>
  "major_city", # <use_zipcoder_tidytable>
  "county", # <use_zipcoder_tidytable>
  "state", # <use_zipcoder_tidytable>
  "lat", # <use_zipcoder_tidytable>
  "lng", # <use_zipcoder_tidytable>
  "bounds_west", # <use_zipcoder_tidytable>
  "bounds_east", # <use_zipcoder_tidytable>
  "bounds_north", # <use_zipcoder_tidytable>
  "bounds_south", # <use_zipcoder_tidytable>
  NULL
))
